### ISSUE TITLE
不能使用哦

### ISSUE THREAD

**Issue by BCsl** [qqliu10u/ResourceDetector#1]
Demo apk 并不能检测到哦

**Comment by qqliu10u** [comment]
不好意思，最近不怎么上github，你是准备收藏tumblr吗？如果是的话，需要到汤上申请下开放平台的id，用起来很溜的。注册方法见：http://www.jianshu.com/p/a2a17d8c5caa。  修改TumblrClient 类的client和token就可以了。

**Comment by qqliu10u** [comment]
Demo apk我没把自己的id放上去，所以运行效果不好。

**Comment by BCsl** [comment]
也不是只是为了收藏 tumblr，只是对这种视频地址检测感兴趣，然后你的文章思路很好，但自己也基本没有前端开发的经验，我看代码最终是检测 video 标签来获取视频地址，不知道是不是说，视频播放最终都用 video 标签来播放的？

**Comment by qqliu10u** [comment]
不是都是video，移动端一般是video和flash两种，但目前video是主流，移动端的flash感觉快要淘汰了。
我本来是准备往webview注入js检测，后来发现有跨域问题，最后改成了这种用webview不断检测里面的链接来探测视频，这种方案不太适合复杂的站点，因为复杂站点提取规则比较麻烦，而且我自己测试发现按同一个规则有些视频检测不到。
